name: Build and Deploy to AWS ECR & Lambda

on:
    push:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: "us-east-1"

            - name: Log in to AWS Public ECR
              run: |
                aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

            - name: Build, Tag and Push image to ECR
              env:
                ECR_REPO_URI: "public.ecr.aws/a5q2p4d5/churn-prediction-api"
              run: |
                echo "Building and tagging image: $ECR_REPO_URI:latest"
                # Build the Docker Image
                docker build -t $ECR_REPO_URI:latest .

                echo "Pushing image to ECR"
                docker push $ECR_REPO_URI:latest

            - name: Update Lambda Function Code
              env:
                ECR_REPO_URI: "public.ecr.aws/a5q2p4d5/churn-prediction-api:latest"
                LAMBDA_FUNCTION_NAME: "churn-prediction-api"
                LAMBDA_REGION: "us-east-1"
              run: |
                echo "Updating Lambda Function: $LAMBDA_FUNCTION_NAME"
                aws lambda update-function-code \
                  --function-name $LAMBDA_FUNCTION_NAME \
                  --image-uri $ECR_REPO_URI \
                  --region $LAMBDA_REGION
                echo "Lambda update complete"